# We must apps 2 variables from cmd args
# 1. component 
# 2. environment

- name: "configure {{ component }} server"
  hosts: all
  become: yes
  vars_files:
    - "variables-{{ environment }}.yaml"
  roles:
    - "{{ component }}"
